// <auto-generated />
using System;
using Control_DINADECO_UCAG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Control_DINADECO_UCAG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241101161033_Seguimiento")]
    partial class Seguimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbActum", b =>
                {
                    b.Property<int>("IdActa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_acta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdActa"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaSesion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_sesion");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<int?>("IdAsociado")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociado");

                    b.Property<int?>("IdConcepto")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_concepto");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NumeroActa")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_acta");

                    b.Property<string>("Observacion")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("observacion");

                    b.HasKey("IdActa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion");

                    b.HasIndex(new[] { "IdAsociado" }, "id_asociado");

                    b.ToTable("tb_acta", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAcuerdo", b =>
                {
                    b.Property<int>("IdAcuerdo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_acuerdo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAcuerdo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdActa")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_acta");

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroAcuerdo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_acuerdo");

                    b.HasKey("IdAcuerdo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdActa" }, "id_acta");

                    b.ToTable("tb_acuerdo", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociacion", b =>
                {
                    b.Property<int>("IdAsociacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsociacion"));

                    b.Property<string>("Canton")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("canton");

                    b.Property<string>("CedulaJuridica")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("cedula_juridica");

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("codigo_registro");

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("distrito");

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fax");

                    b.Property<DateOnly?>("FechaConstitucion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_constitucion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provincia");

                    b.Property<string>("Pueblo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pueblo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdAsociacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CedulaJuridica" }, "cedula_juridica")
                        .IsUnique();

                    b.HasIndex(new[] { "CodigoRegistro" }, "codigo_registro")
                        .IsUnique();

                    b.ToTable("tb_asociacion", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociacionWeb", b =>
                {
                    b.Property<int>("IdAsocWeb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asoc_web");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsocWeb"));

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<string>("Latitud")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("latitud");

                    b.Property<string>("Longitud")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("longitud");

                    b.HasKey("IdAsocWeb")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion1");

                    b.ToTable("tb_asociacion_web", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociado", b =>
                {
                    b.Property<int>("IdAsociado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsociado"));

                    b.Property<string>("Apellido1")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("apellido_1");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("apellido_2");

                    b.Property<string>("Cedula")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("cedula");

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado_civil");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("Sexo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("telefono");

                    b.HasKey("IdAsociado")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion2");

                    b.ToTable("tb_asociado", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAtractivo", b =>
                {
                    b.Property<int>("IdAtractivos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_atractivos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAtractivos"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("IdAsocWeb")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asoc_web");

                    b.Property<string>("Latitud")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("latitud");

                    b.Property<string>("Longitud")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("longitud");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo");

                    b.HasKey("IdAtractivos")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsocWeb" }, "id_asoc_web");

                    b.ToTable("tb_atractivos", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCheque", b =>
                {
                    b.Property<int>("IdCheque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cheque");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCheque"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdCuenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cuenta");

                    b.Property<int?>("IdGirado")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_girado");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("monto");

                    b.Property<int>("NoCheque")
                        .HasColumnType("int(11)")
                        .HasColumnName("no_cheque");

                    b.HasKey("IdCheque")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCuenta" }, "id_cuenta");

                    b.HasIndex(new[] { "IdGirado" }, "id_girado");

                    b.HasIndex(new[] { "NoCheque" }, "no_cheque")
                        .IsUnique();

                    b.ToTable("tb_cheque", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido_1");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido_2");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente")
                        .HasName("PRIMARY");

                    b.ToTable("tb_cliente", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbConcepto", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_concepto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConcepto"));

                    b.Property<bool?>("Aplicacion2")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aplicacion_2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.HasKey("IdConcepto")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion3");

                    b.ToTable("tb_concepto", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCuentum", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cuenta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCuenta"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<int>("NumeroCuenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("numero_cuenta");

                    b.Property<decimal?>("Saldo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("saldo");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo");

                    b.HasKey("IdCuenta")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion4");

                    b.HasIndex(new[] { "NumeroCuenta" }, "numero_cuenta")
                        .IsUnique();

                    b.ToTable("tb_cuenta", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDetalleEgreso", b =>
                {
                    b.Property<int>("IdDetalleEgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_detalle_egreso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleEgreso"));

                    b.Property<int?>("IdInformeEconomico")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_informe_economico");

                    b.Property<int?>("IdMovimientoEgreso")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_movimiento_egreso");

                    b.Property<decimal?>("Total")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("total");

                    b.HasKey("IdDetalleEgreso")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdInformeEconomico" }, "id_informe_economico");

                    b.HasIndex(new[] { "IdMovimientoEgreso" }, "id_movimiento_egreso");

                    b.ToTable("tb_detalle_egreso", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_factura");

                    b.Property<decimal?>("MontoTotal")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("monto_total");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFactura" }, "id_factura");

                    b.ToTable("tb_detalle_factura", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDetalleIngreso", b =>
                {
                    b.Property<int>("IdDetalleIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_detalle_ingreso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleIngreso"));

                    b.Property<int?>("IdInformeEconomico")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_informe_economico");

                    b.Property<int?>("IdMovimientoIngreso")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_movimiento_ingreso");

                    b.Property<decimal?>("Total")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("total");

                    b.HasKey("IdDetalleIngreso")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdInformeEconomico" }, "id_informe_economico")
                        .HasDatabaseName("id_informe_economico1");

                    b.HasIndex(new[] { "IdMovimientoIngreso" }, "id_movimiento_ingreso");

                    b.ToTable("tb_detalle_ingreso", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDocumento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_documento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_factura");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numero_documento");

                    b.Property<decimal?>("Total")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("total");

                    b.HasKey("IdDocumento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion5");

                    b.HasIndex(new[] { "IdFactura" }, "id_factura")
                        .HasDatabaseName("id_factura1");

                    b.ToTable("tb_documento", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbFactura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_factura");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<decimal?>("Descuento")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("descuento");

                    b.Property<string>("Detalle")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("detalle");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdConcepto")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_concepto");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal?>("Impuestos")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("impuestos");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numero_factura");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Total")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdConcepto" }, "id_concepto");

                    b.HasIndex(new[] { "IdProveedor" }, "id_proveedor");

                    b.ToTable("tb_factura", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbFoto", b =>
                {
                    b.Property<int>("IdFotos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_fotos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFotos"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdAtractivos")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_atractivos");

                    b.Property<string>("RutaFoto")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("ruta_foto");

                    b.HasKey("IdFotos")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAtractivos" }, "id_atractivos");

                    b.ToTable("tb_fotos", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbInformeEconomico", b =>
                {
                    b.Property<int>("IdInformeEconomico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_informe_economico");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInformeEconomico"));

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaActualizacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateOnly?>("FechaInforme")
                        .HasColumnType("date")
                        .HasColumnName("fecha_informe");

                    b.Property<int?>("IdActa")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_acta");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<decimal?>("TotalEgresos")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("total_egresos");

                    b.Property<decimal?>("TotalIngresos")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("total_ingresos");

                    b.HasKey("IdInformeEconomico")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdActa" }, "id_acta")
                        .HasDatabaseName("id_acta1");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion6");

                    b.ToTable("tb_informe_economico", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbJuntaDirectiva", b =>
                {
                    b.Property<int>("IdJuntaDirectiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_junta_directiva");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdJuntaDirectiva"));

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado");

                    b.Property<int?>("IdActa")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_acta");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<DateOnly?>("PeriodoFin")
                        .HasColumnType("date")
                        .HasColumnName("periodo_fin");

                    b.Property<DateOnly?>("PeriodoInicio")
                        .HasColumnType("date")
                        .HasColumnName("periodo_inicio");

                    b.HasKey("IdJuntaDirectiva")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdActa" }, "id_acta")
                        .HasDatabaseName("id_acta2");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .IsUnique()
                        .HasDatabaseName("id_asociacion7");

                    b.ToTable("tb_junta_directiva", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMiembrosJuntaDirectiva", b =>
                {
                    b.Property<int>("IdMiembrosJuntaDirectiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_miembros_junta_directiva");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMiembrosJuntaDirectiva"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("IdAsociado")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociado");

                    b.Property<int?>("IdJuntaDirectiva")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_junta_directiva");

                    b.Property<int?>("IdPuesto")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_puesto");

                    b.HasKey("IdMiembrosJuntaDirectiva")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociado" }, "id_asociado")
                        .HasDatabaseName("id_asociado1");

                    b.HasIndex(new[] { "IdJuntaDirectiva" }, "id_junta_directiva");

                    b.HasIndex(new[] { "IdPuesto" }, "id_puesto");

                    b.ToTable("tb_miembros_junta_directiva", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMovimientoEgreso", b =>
                {
                    b.Property<int>("IdMovimientosEgresos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_movimientos_egresos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMovimientosEgresos"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdActa")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_acta");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<int?>("IdCheque")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cheque");

                    b.Property<int?>("IdCuenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cuenta");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_factura");

                    b.Property<int?>("IdTipoMovimiento")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_tipo_movimiento");

                    b.HasKey("IdMovimientosEgresos")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdActa" }, "id_acta")
                        .HasDatabaseName("id_acta3");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion8");

                    b.HasIndex(new[] { "IdCheque" }, "id_cheque");

                    b.HasIndex(new[] { "IdCuenta" }, "id_cuenta")
                        .HasDatabaseName("id_cuenta1");

                    b.HasIndex(new[] { "IdFactura" }, "id_factura")
                        .HasDatabaseName("id_factura2");

                    b.HasIndex(new[] { "IdTipoMovimiento" }, "id_tipo_movimiento");

                    b.ToTable("tb_movimiento_egresos", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMovimientoIngreso", b =>
                {
                    b.Property<int>("IdMovimientoIngresos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_movimiento_ingresos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMovimientoIngresos"));

                    b.Property<string>("Detalle")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("detalle");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaComprobante")
                        .HasColumnType("date")
                        .HasColumnName("fecha_comprobante");

                    b.Property<int?>("IdActa")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_acta");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdConcepto")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_concepto");

                    b.Property<int?>("IdCuenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cuenta");

                    b.Property<int?>("IdDocumento")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_documento");

                    b.Property<int?>("IdTipoMovimientos")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_tipo_movimientos");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdMovimientoIngresos")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdActa" }, "id_acta")
                        .HasDatabaseName("id_acta4");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion9");

                    b.HasIndex(new[] { "IdCliente" }, "id_cliente");

                    b.HasIndex(new[] { "IdConcepto" }, "id_concepto")
                        .HasDatabaseName("id_concepto1");

                    b.HasIndex(new[] { "IdCuenta" }, "id_cuenta")
                        .HasDatabaseName("id_cuenta2");

                    b.HasIndex(new[] { "IdDocumento" }, "id_documento");

                    b.HasIndex(new[] { "IdTipoMovimientos" }, "id_tipo_movimientos");

                    b.ToTable("tb_movimiento_ingresos", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbProveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Cedula")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("cedula");

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("Fax")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("fax");

                    b.Property<int?>("IdAsociacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_asociacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsociacion" }, "id_asociacion")
                        .HasDatabaseName("id_asociacion10");

                    b.ToTable("tb_proveedor", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbPuesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_puesto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPuesto")
                        .HasName("PRIMARY");

                    b.ToTable("tb_puesto", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbTipoMovimiento", b =>
                {
                    b.Property<int>("IdTipoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_tipo_movimiento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoMovimiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdTipoMovimiento")
                        .HasName("PRIMARY");

                    b.ToTable("tb_tipo_movimiento", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbUsuario", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_user");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Contraseña")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("IdUser")
                        .HasName("PRIMARY");

                    b.ToTable("tb_usuario", (string)null);
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbActum", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbActa")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_acta_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociado", "IdAsociadoNavigation")
                        .WithMany("TbActa")
                        .HasForeignKey("IdAsociado")
                        .HasConstraintName("tb_acta_ibfk_1");

                    b.Navigation("IdAsociacionNavigation");

                    b.Navigation("IdAsociadoNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAcuerdo", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbActum", "IdActaNavigation")
                        .WithMany("TbAcuerdos")
                        .HasForeignKey("IdActa")
                        .HasConstraintName("tb_acuerdo_ibfk_1");

                    b.Navigation("IdActaNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociacionWeb", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbAsociacionWebs")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_asociacion_web_ibfk_1");

                    b.Navigation("IdAsociacionNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociado", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbAsociados")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_asociado_ibfk_1");

                    b.Navigation("IdAsociacionNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAtractivo", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacionWeb", "IdAsocWebNavigation")
                        .WithMany("TbAtractivos")
                        .HasForeignKey("IdAsocWeb")
                        .HasConstraintName("tb_atractivos_ibfk_1");

                    b.Navigation("IdAsocWebNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCheque", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbCuentum", "IdCuentaNavigation")
                        .WithMany("TbCheques")
                        .HasForeignKey("IdCuenta")
                        .HasConstraintName("tb_cheque_ibfk_1");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbProveedor", "IdGiradoNavigation")
                        .WithMany("TbCheques")
                        .HasForeignKey("IdGirado")
                        .HasConstraintName("tb_cheque_ibfk_2");

                    b.Navigation("IdCuentaNavigation");

                    b.Navigation("IdGiradoNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbConcepto", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbConceptos")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_concepto_ibfk_1");

                    b.Navigation("IdAsociacionNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCuentum", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbCuenta")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_cuenta_ibfk_1");

                    b.Navigation("IdAsociacionNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDetalleEgreso", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbInformeEconomico", "IdInformeEconomicoNavigation")
                        .WithMany("TbDetalleEgresos")
                        .HasForeignKey("IdInformeEconomico")
                        .HasConstraintName("tb_detalle_egreso_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbMovimientoEgreso", "IdMovimientoEgresoNavigation")
                        .WithMany("TbDetalleEgresos")
                        .HasForeignKey("IdMovimientoEgreso")
                        .HasConstraintName("tb_detalle_egreso_ibfk_1");

                    b.Navigation("IdInformeEconomicoNavigation");

                    b.Navigation("IdMovimientoEgresoNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDetalleFactura", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbFactura", "IdFacturaNavigation")
                        .WithMany("TbDetalleFacturas")
                        .HasForeignKey("IdFactura")
                        .HasConstraintName("tb_detalle_factura_ibfk_1");

                    b.Navigation("IdFacturaNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDetalleIngreso", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbInformeEconomico", "IdInformeEconomicoNavigation")
                        .WithMany("TbDetalleIngresos")
                        .HasForeignKey("IdInformeEconomico")
                        .HasConstraintName("tb_detalle_ingreso_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbMovimientoIngreso", "IdMovimientoIngresoNavigation")
                        .WithMany("TbDetalleIngresos")
                        .HasForeignKey("IdMovimientoIngreso")
                        .HasConstraintName("tb_detalle_ingreso_ibfk_1");

                    b.Navigation("IdInformeEconomicoNavigation");

                    b.Navigation("IdMovimientoIngresoNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDocumento", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbDocumentos")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_documento_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbFactura", "IdFacturaNavigation")
                        .WithMany("TbDocumentos")
                        .HasForeignKey("IdFactura")
                        .HasConstraintName("tb_documento_ibfk_1");

                    b.Navigation("IdAsociacionNavigation");

                    b.Navigation("IdFacturaNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbFactura", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbConcepto", "IdConceptoNavigation")
                        .WithMany("TbFacturas")
                        .HasForeignKey("IdConcepto")
                        .HasConstraintName("tb_factura_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbProveedor", "IdProveedorNavigation")
                        .WithMany("TbFacturas")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("tb_factura_ibfk_1");

                    b.Navigation("IdConceptoNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbFoto", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAtractivo", "IdAtractivosNavigation")
                        .WithMany("TbFotos")
                        .HasForeignKey("IdAtractivos")
                        .HasConstraintName("tb_fotos_ibfk_1");

                    b.Navigation("IdAtractivosNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbInformeEconomico", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbActum", "IdActaNavigation")
                        .WithMany("TbInformeEconomicos")
                        .HasForeignKey("IdActa")
                        .HasConstraintName("tb_informe_economico_ibfk_1");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbInformeEconomicos")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_informe_economico_ibfk_2");

                    b.Navigation("IdActaNavigation");

                    b.Navigation("IdAsociacionNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbJuntaDirectiva", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbActum", "IdActaNavigation")
                        .WithMany("TbJuntaDirectivas")
                        .HasForeignKey("IdActa")
                        .HasConstraintName("tb_junta_directiva_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithOne("TbJuntaDirectiva")
                        .HasForeignKey("Control_DINADECO_UCAG.Models.TbJuntaDirectiva", "IdAsociacion")
                        .HasConstraintName("tb_junta_directiva_ibfk_1");

                    b.Navigation("IdActaNavigation");

                    b.Navigation("IdAsociacionNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMiembrosJuntaDirectiva", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociado", "IdAsociadoNavigation")
                        .WithMany("TbMiembrosJuntaDirectivas")
                        .HasForeignKey("IdAsociado")
                        .HasConstraintName("tb_miembros_junta_directiva_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbJuntaDirectiva", "IdJuntaDirectivaNavigation")
                        .WithMany("TbMiembrosJuntaDirectivas")
                        .HasForeignKey("IdJuntaDirectiva")
                        .HasConstraintName("tb_miembros_junta_directiva_ibfk_1");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbPuesto", "IdPuestoNavigation")
                        .WithMany("TbMiembrosJuntaDirectivas")
                        .HasForeignKey("IdPuesto")
                        .HasConstraintName("tb_miembros_junta_directiva_ibfk_3");

                    b.Navigation("IdAsociadoNavigation");

                    b.Navigation("IdJuntaDirectivaNavigation");

                    b.Navigation("IdPuestoNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMovimientoEgreso", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbActum", "IdActaNavigation")
                        .WithMany("TbMovimientoEgresos")
                        .HasForeignKey("IdActa")
                        .HasConstraintName("tb_movimiento_egresos_ibfk_5");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbMovimientoEgresos")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_movimiento_egresos_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbCheque", "IdChequeNavigation")
                        .WithMany("TbMovimientoEgresos")
                        .HasForeignKey("IdCheque")
                        .HasConstraintName("tb_movimiento_egresos_ibfk_4");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbCuentum", "IdCuentaNavigation")
                        .WithMany("TbMovimientoEgresos")
                        .HasForeignKey("IdCuenta")
                        .HasConstraintName("tb_movimiento_egresos_ibfk_3");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbFactura", "IdFacturaNavigation")
                        .WithMany("TbMovimientoEgresos")
                        .HasForeignKey("IdFactura")
                        .HasConstraintName("tb_movimiento_egresos_ibfk_6");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbTipoMovimiento", "IdTipoMovimientoNavigation")
                        .WithMany("TbMovimientoEgresos")
                        .HasForeignKey("IdTipoMovimiento")
                        .HasConstraintName("tb_movimiento_egresos_ibfk_1");

                    b.Navigation("IdActaNavigation");

                    b.Navigation("IdAsociacionNavigation");

                    b.Navigation("IdChequeNavigation");

                    b.Navigation("IdCuentaNavigation");

                    b.Navigation("IdFacturaNavigation");

                    b.Navigation("IdTipoMovimientoNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMovimientoIngreso", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbActum", "IdActaNavigation")
                        .WithMany("TbMovimientoIngresos")
                        .HasForeignKey("IdActa")
                        .HasConstraintName("tb_movimiento_ingresos_ibfk_7");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbMovimientoIngresos")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_movimiento_ingresos_ibfk_2");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbCliente", "IdClienteNavigation")
                        .WithMany("TbMovimientoIngresos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("tb_movimiento_ingresos_ibfk_5");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbConcepto", "IdConceptoNavigation")
                        .WithMany("TbMovimientoIngresos")
                        .HasForeignKey("IdConcepto")
                        .HasConstraintName("tb_movimiento_ingresos_ibfk_4");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbCuentum", "IdCuentaNavigation")
                        .WithMany("TbMovimientoIngresos")
                        .HasForeignKey("IdCuenta")
                        .HasConstraintName("tb_movimiento_ingresos_ibfk_3");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbDocumento", "IdDocumentoNavigation")
                        .WithMany("TbMovimientoIngresos")
                        .HasForeignKey("IdDocumento")
                        .HasConstraintName("tb_movimiento_ingresos_ibfk_6");

                    b.HasOne("Control_DINADECO_UCAG.Models.TbTipoMovimiento", "IdTipoMovimientosNavigation")
                        .WithMany("TbMovimientoIngresos")
                        .HasForeignKey("IdTipoMovimientos")
                        .HasConstraintName("tb_movimiento_ingresos_ibfk_1");

                    b.Navigation("IdActaNavigation");

                    b.Navigation("IdAsociacionNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdConceptoNavigation");

                    b.Navigation("IdCuentaNavigation");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdTipoMovimientosNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbProveedor", b =>
                {
                    b.HasOne("Control_DINADECO_UCAG.Models.TbAsociacion", "IdAsociacionNavigation")
                        .WithMany("TbProveedors")
                        .HasForeignKey("IdAsociacion")
                        .HasConstraintName("tb_proveedor_ibfk_1");

                    b.Navigation("IdAsociacionNavigation");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbActum", b =>
                {
                    b.Navigation("TbAcuerdos");

                    b.Navigation("TbInformeEconomicos");

                    b.Navigation("TbJuntaDirectivas");

                    b.Navigation("TbMovimientoEgresos");

                    b.Navigation("TbMovimientoIngresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociacion", b =>
                {
                    b.Navigation("TbActa");

                    b.Navigation("TbAsociacionWebs");

                    b.Navigation("TbAsociados");

                    b.Navigation("TbConceptos");

                    b.Navigation("TbCuenta");

                    b.Navigation("TbDocumentos");

                    b.Navigation("TbInformeEconomicos");

                    b.Navigation("TbJuntaDirectiva");

                    b.Navigation("TbMovimientoEgresos");

                    b.Navigation("TbMovimientoIngresos");

                    b.Navigation("TbProveedors");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociacionWeb", b =>
                {
                    b.Navigation("TbAtractivos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAsociado", b =>
                {
                    b.Navigation("TbActa");

                    b.Navigation("TbMiembrosJuntaDirectivas");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbAtractivo", b =>
                {
                    b.Navigation("TbFotos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCheque", b =>
                {
                    b.Navigation("TbMovimientoEgresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCliente", b =>
                {
                    b.Navigation("TbMovimientoIngresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbConcepto", b =>
                {
                    b.Navigation("TbFacturas");

                    b.Navigation("TbMovimientoIngresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbCuentum", b =>
                {
                    b.Navigation("TbCheques");

                    b.Navigation("TbMovimientoEgresos");

                    b.Navigation("TbMovimientoIngresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbDocumento", b =>
                {
                    b.Navigation("TbMovimientoIngresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbFactura", b =>
                {
                    b.Navigation("TbDetalleFacturas");

                    b.Navigation("TbDocumentos");

                    b.Navigation("TbMovimientoEgresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbInformeEconomico", b =>
                {
                    b.Navigation("TbDetalleEgresos");

                    b.Navigation("TbDetalleIngresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbJuntaDirectiva", b =>
                {
                    b.Navigation("TbMiembrosJuntaDirectivas");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMovimientoEgreso", b =>
                {
                    b.Navigation("TbDetalleEgresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbMovimientoIngreso", b =>
                {
                    b.Navigation("TbDetalleIngresos");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbProveedor", b =>
                {
                    b.Navigation("TbCheques");

                    b.Navigation("TbFacturas");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbPuesto", b =>
                {
                    b.Navigation("TbMiembrosJuntaDirectivas");
                });

            modelBuilder.Entity("Control_DINADECO_UCAG.Models.TbTipoMovimiento", b =>
                {
                    b.Navigation("TbMovimientoEgresos");

                    b.Navigation("TbMovimientoIngresos");
                });
#pragma warning restore 612, 618
        }
    }
}
